Update create and console bash

diff --git a/create b/create
--- a/create
+++ b/create
@@ -5,7 +5,9 @@ source ./scripts/checker
 #default由container內的laravel install安裝Laravel
 export LARAVEL_INSTALLER='container'
 if [ -f "${base_path}/.env" ]; then
-source ${base_path}/.env
+  source ${base_path}/.env
+  else
+  base_path="$( cd "$(dirname "$0")" ; pwd -P )" 
 fi
 
 #is windows
@@ -87,6 +89,8 @@ function dlaravelconfig {
         fi
         ${winpty} docker-compose exec -u dlaravel php sed -i "s/DB_HOST=127.0.0.1/DB_HOST=db/" /var/www/html/${@}/.env
         ${winpty} docker-compose exec -u dlaravel php sed -i "s/DB_DATABASE=homestead/DB_DATABASE=${@}/" /var/www/html/${@}/.env
+        ${winpty} docker-compose exec -u dlaravel php sed -i "s/DB_USERNAME=homestead/DB_USERNAME=${@}/" /var/www/html/${@}/.env
+        ${winpty} docker-compose exec -u dlaravel php sed -i "s/DB_PASSWORD=secret/DB_PASSWORD=${@}/" /var/www/html/${@}/.env
         
         #docker-compose exec php /root/.composer/vendor/bin/laravel new ${1}
         #調整資料庫連線到db的container
@@ -101,26 +105,38 @@ function dlaravelconfig {
 
       sed -i "s/DB_HOST=127.0.0.1/DB_HOST=db/" sites/${@}/.env
       sed -i "s/DB_DATABASE=homestead/DB_DATABASE=${@}/" sites/${@}/.env
+      sed -i "s/DB_USERNAME=homestead/DB_USERNAME=${@}/" sites/${@}/.env
+      sed -i "s/DB_PASSWORD=homestead/DB_PASSWORD=${@}/" sites/${@}/.env
 
     fi
 
+    #檢測container內是否有給MYSQL_ROOT_PASSWORD
+    ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db env|grep MYSQL_ROOT_PASSWORD >/dev/null 2>&1
 
-    if [ -z "${MYSQL_ROOT_PASSWORD}" ]; then
+    #RTOO沒設定密碼
+    if [ $? -gt 0 ]; then
 
         #建資料庫
         ${winpty} docker-compose exec db mysql -e "CREATE DATABASE IF NOT EXISTS \`${1}\`"
-        #授權
-        ${winpty} docker-compose exec db mysql -e "grant all on \`${1}\`.* to 'homestead'@'%' IDENTIFIED by 'secret'"
+        #建立使用者
+        ${winpty} docker-compose exec db mysql -e "CREATE USER IF NOT EXISTS \"${1}\""
+        #設定使用者帳密同Project名稱
+        ${winpty} docker-compose exec db mysql -e "SET PASSWORD FOR \`${1}\`=\"${1}\""
+        #授權使用者
+        ${winpty} docker-compose exec db mysql -e "GRANT ALL ON \`${1}\`.* TO \"${1}\""
         #更新container權限
         ${winpty} docker-compose exec db mysql -e "FLUSH PRIVILEGES"
         else
         #建資料庫
-        ${winpty} docker-compose exec db mysql -e "CREATE DATABASE IF NOT EXISTS \`${1}\`" -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1
-        #授權
-        ${winpty} docker-compose exec db mysql -e "grant all on \`${1}\`.* to 'homestead'@'%' IDENTIFIED by 'secret'" -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1
-
+        ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "CREATE DATABASE IF NOT EXISTS \`'${1}'\`" -uroot -p"$MYSQL_ROOT_PASSWORD"' >/dev/null 2>&1
+        #建立使用者
+        ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "CREATE USER IF NOT EXISTS \"'${1}'\"" -uroot -p"$MYSQL_ROOT_PASSWORD"' >/dev/null 2>&1
+        #設定使用者帳密同Project名稱
+        ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "SET PASSWORD FOR \`'${1}'\`=\"'${1}'\"" -uroot -p"$MYSQL_ROOT_PASSWORD"' >/dev/null 2>&1  
+        #授權使用者
+        ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "GRANT ALL ON \`'${1}'\`.* TO \"'${1}'\"" -uroot -p"$MYSQL_ROOT_PASSWORD"' >/dev/null 2>&1
         #更新container權限
-        ${winpty} docker-compose exec db mysql -e "FLUSH PRIVILEGES" -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1
+        ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "FLUSH PRIVILEGES" -uroot -p"$MYSQL_ROOT_PASSWORD"' >/dev/null 2>&1
 
     fi
 
@@ -191,6 +207,8 @@ if [ "$#" -eq 2 ]; then
 
     if [ "${1}" = "--db" ]; then
         is_running
+        MYSQL_ROOT_PASSWORD=`${winpty} docker-compose -f docker-compose.yml exec db env|grep MYSQL_ROOT_PASSWORD|cut -d= -f2`
+
         if [ -z "${MYSQL_ROOT_PASSWORD}" ]; then
             #建立資料庫，如果不存在
             ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "CREATE DATABASE IF NOT EXISTS \`${2}\`"
@@ -202,18 +220,22 @@ if [ "$#" -eq 2 ]; then
             ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "GRANT ALL ON \`${2}\`.* TO \"${2}\""
             #更新container權限
             ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "FLUSH PRIVILEGES"
-            else
-            #建立資料庫，如果不存在
-            ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "CREATE DATABASE IF NOT EXISTS \`${2}\`" -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1
+        else
+            #建資料庫
+            ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "CREATE DATABASE IF NOT EXISTS \`'${2}'\`" -uroot -p"$MYSQL_ROOT_PASSWORD"' > /dev/null 2>&1
             #建立使用者
-            ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "CREATE USER IF NOT EXISTS \"${2}\"" -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1
-            #建立密碼，同使用者名稱
-            ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "SET PASSWORD FOR \`${2}\`=\"${2}\"" -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1
-            #授權
-            ${winpty} docker-compose -f docker-compose.yml exec db mysql  -e "GRANT ALL ON \`${2}\`.* TO \"${2}\"" -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1
+            ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "CREATE USER IF NOT EXISTS \"'${2}'\""  -uroot -p"$MYSQL_ROOT_PASSWORD"' > /dev/null 2>&1
+            #設定使用者帳密同Project名稱
+            ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "SET PASSWORD FOR \`'${2}'\`=\"'${2}'\""  -uroot -p"$MYSQL_ROOT_PASSWORD"' > /dev/null 2>&1
+            #授權使用者
+            ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "GRANT ALL ON \`'${2}'\`.* TO \"'${2}'\""  -uroot -p"$MYSQL_ROOT_PASSWORD"' > /dev/null 2>&1
             #更新container權限
-            ${winpty} docker-compose -f docker-compose.yml exec db mysql  -e "FLUSH PRIVILEGES" -uroot -p${MYSQL_ROOT_PASSWORD}  > /dev/null 2>&1
+            ${winpty} docker-compose -f ${base_path}/docker-compose.yml exec db sh -c 'mysql -e "FLUSH PRIVILEGES"  -uroot -p"$MYSQL_ROOT_PASSWORD"' > /dev/null 2>&1
 
+            if [ $? -eq 1 ]; then
+                echo "CREATE DATABASE failed. Please try restart your container."
+                exit;
+            fi
         fi
 
         echo "Done."
