fix creat new laravel project on Windows 10

diff --git a/create b/create
--- a/create
+++ b/create
@@ -42,8 +42,8 @@ fi
 
 #docker-compose exec php /root/.composer/vendor/bin/laravel new ${1}
 #調整資料庫連線到db的container
-docker-compose exec php sudo -u dlaravel sed -i "s/DB_HOST=127.0.0.1/DB_HOST=db/" /var/www/html/${1}/.env
-docker-compose exec php sudo -u dlaravel sed -i "s/DB_DATABASE=homestead/DB_DATABASE=${1}/" /var/www/html/${1}/.env
+${winpty} docker-compose exec php sudo -u dlaravel sed -i "s/DB_HOST=127.0.0.1/DB_HOST=db/" /var/www/html/${1}/.env
+${winpty} docker-compose exec php sudo -u dlaravel sed -i "s/DB_DATABASE=homestead/DB_DATABASE=${1}/" /var/www/html/${1}/.env
 
     else
       #for windows 10
@@ -90,19 +90,27 @@ web_port=`docker inspect --format='{{(index (index .NetworkSettings.Ports "80/tc
 function dlaravel_new {
     if [ ${hosts_file} == '/etc/hosts' ]; then
         echo "Run laravel installer in container: laravel new ${1}"
-	plateform=`uname -s`
-	if [ ${plateform} == 'Linux' ]; then
-	   chmod 777 etc/cache 
+
+	    plateform=`uname -s`
+	    if [ ${plateform} == 'Linux' ]; then
+	        chmod 777 etc/cache 
         fi
         #確保ubuntu環境能順利寫入資料
-	${winpty} docker-compose exec php chown dlaravel /var/www/html
+	    ${winpty} docker-compose exec php chown dlaravel /var/www/html
         #確保dlaravel有權限寫入/var/log，例如xdebug.log
-	${winpty} docker-compose exec php chown dlaravel /var/log
+	    ${winpty} docker-compose exec php chown dlaravel /var/log
         docker exec -ti ${containerName}_php_1 sudo -u dlaravel /home/dlaravel/.composer/vendor/bin/laravel new ${1}
     else
-        echo "Please install laravel installer on Windows 10"
-        echo "or you can manually run laravel installer in the php container"
-        exit;
+
+    which laravel >/dev/null 2>&1
+
+    if [ $? -eq 0 ]; then
+        laravel new sites/${1}
+    else
+        echo "Please install laravel installer from gitbash on Windows 10"
+        echo "or you can manually run laravel installer in the php container and create database by yourself."
+        exit
+        fi
     fi
 }
 
@@ -216,23 +224,118 @@ if [ $? -eq 1 ]; then
     fi
 fi
 
+#dlaravel_new ${1}
+
+#create --host
+if [ "$#" -eq 2 ]; then
+    if [ "${1}" = "--db" ]; then
+        #建立資料庫，如果不存在
+        ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "CREATE DATABASE IF NOT EXISTS \`${2}\`"
+
+        #建立使用者
+        ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "CREATE USER IF NOT EXISTS \"${2}\""
+        #建立密碼，同使用者名稱
+        ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "SET PASSWORD FOR \`${2}\`=\"${2}\""
+        #授權
+        ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "GRANT ALL ON \`${2}\`.* TO \"${2}\""
+        #更新container權限
+        ${winpty} docker-compose -f docker-compose.yml exec db mysql -e "FLUSH PRIVILEGES"
+        echo "Done."
+        exit;
+    fi
+    if [ "${1}" = "--host" ]; then
+            
+            if [ ${hosts_file} == '/etc/hosts' ]; then
+                sudo cat /etc/hosts|tr -s " "|grep "127.0.0.1 ${2}.dev"
+                #找不到時，就新增至Hosts
+                if [ $? -eq 1 ]; then
+                echo "127.0.0.1 ${2}.dev" |sudo tee -a /etc/hosts
+                fi
+                else
+
+                #for windows 10
+                cat /c/Windows/System32/drivers/etc/hosts|grep "127.0.0.1 ${2}.dev"
+                if [ $? -eq 1 ]; then
+                echo 127.0.0.1 ${2}.dev >> /c/Windows/System32/drivers/etc/hosts  
+                fi
+            fi
+
+            docker ps |grep -q ${containerName}_php_1
+            if [ $? -eq 0 ]; then
+                source ./scripts/nginx-reload
+            fi
+        echo "To manually create new empty project:"
+        echo "mkdir -p sites/${2}/public;touch sites/${2}/public/index.php"
+        exit
+    fi
+
+    echo "./create --conf ['project name']"
+    exit
+fi
+
+#只建立nginx的設定檔
+if [ "$#" -eq 2 ]; then
+    if [ "${1}" = "--conf" ]; then
+            
+            if [ ${hosts_file} == '/etc/hosts' ]; then
+                sudo cat /etc/hosts|tr -s " "|grep "127.0.0.1 ${2}.dev"
+                #找不到時，就新增至Hosts
+                if [ $? -eq 1 ]; then
+                echo "127.0.0.1 ${2}.dev" |sudo tee -a /etc/hosts
+                fi
+                else
+
+                #for windows 10
+                cat /c/Windows/System32/drivers/etc/hosts|grep "127.0.0.1 ${2}.dev"
+                if [ $? -eq 1 ]; then
+                echo 127.0.0.1 ${2}.dev >> /c/Windows/System32/drivers/etc/hosts  
+                fi
+            fi
+
+            docker ps |grep -q ${containerName}_php_1
+            if [ $? -eq 0 ]; then
+                source ./scripts/nginx-reload
+            fi
+        echo "To manually create new empty project:"
+        echo "mkdir -p sites/${2}/public;touch sites/${2}/public/index.php"
+        exit
+    fi
+
+    echo "./create --conf ['project name']"
+    exit
+fi
+
+#資料夾不能有 . 
+if [[ "${1}" =~ [\.] ]]; then
+    echo "Can't have dot in Project name."
+    exit;
+fi
+
+#檢測目錄是否已存在
+if [ -e "sites/${1}" ]; then
+    echo "The sites/${1} folder exists"
+    exit
+fi
+
+
+#檢測是否執行
+docker-compose  -f docker-compose.yml ps |grep ${containerName}_web_1|grep -q Up
+if [ $? -eq 1 ]; then
+    echo "${containerName}_php_1 is not running."
+    echo "Would you like to create the project and run docker-compose up (y/n):"
+    read  ans
+    if [ ${ans} = 'n' ]; then
+       exit
+    else 
+       docker-compose up -d
+        if [ ${?} -ne 0 ]; then
+            #啟動失敗，停止動作
+            exit;
+        fi
+    fi
+fi
+
+#install new laravel project
 dlaravel_new ${1}
 
-#安裝新的Laravel
-#檢測本機是否安裝laravel installer
-
-#停用下方程式，一律改用container內的laravel installer安裝
-#which laravel >/dev/null 2>&1
-#if [ $? -eq 1 ]; then
-#        dlaravel_new ${1}
-#    else
-#    #加速安裝，使用Mac系統上的laravel installer
-#    laravel new sites/${1}
-#    #falback用container內的laravel
-#    if [ ${?} -ne 0 ]; then
-#        echo "Failback to run installer from container."
-#        dlaravel_new ${1}
-#    fi
-#fi
-
-dlaravelconfig  ${1}
+dlaravelconfig ${1}
